"""Add user autosync settings

Revision ID: 3c2e8fc45e2d
Revises: 001
Create Date: 2026-01-10 14:05:07.815169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2e8fc45e2d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('autosync_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sync_interval_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_sync_at')
    op.drop_column('users', 'sync_interval_minutes')
    op.drop_column('users', 'autosync_enabled')
    # ### end Alembic commands ###
