"""Add title and updated_at to conversations

Revision ID: 889e18cccf5d
Revises: 3c2e8fc45e2d
Create Date: 2026-01-11 01:23:27.198476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889e18cccf5d'
down_revision: Union[str, None] = '3c2e8fc45e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
